/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        // Aura Global Design System Colors
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#d0c5af',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#99907c',
        'outline-variant': '#4d4635',
        'surface-tint': '#e9c349',
        primary: '#f2ca50',
        'on-primary': '#3c2f00',
        'primary-container': '#d4af37',
        'on-primary-container': '#554300',
        'inverse-primary': '#735c00',
        secondary: '#c6c6c6',
        'on-secondary': '#2f3131',
        'secondary-container': '#484949',
        'on-secondary-container': '#b8b8b8',
        tertiary: '#bfcdff',
        'on-tertiary': '#082b72',
        'tertiary-container': '#97b0ff',
        'on-tertiary-container': '#254188',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffe088',
        'primary-fixed-dim': '#e9c349',
        'on-primary-fixed': '#241a00',
        'on-primary-fixed-variant': '#574500',
        'secondary-fixed': '#e3e2e2',
        'secondary-fixed-dim': '#c6c6c6',
        'on-secondary-fixed': '#1a1c1c',
        'on-secondary-fixed-variant': '#464747',
        'tertiary-fixed': '#dbe1ff',
        'tertiary-fixed-dim': '#b4c5ff',
        'on-tertiary-fixed': '#00174b',
        'on-tertiary-fixed-variant': '#27438a',
        background: '#131313',
        'on-background': '#e5e2e1',
        'surface-variant': '#353534',
        'rich-black': '#000000',
        'charcoal-surface': '#1E1E1E',
        'metallic-blue': '#2C3E50',
        'gold-pressed': '#C5A028',
      },
      fontFamily: {
        'libre-caslon': ['"Libre Caslon Text"', 'serif'],
        'hanken-grotesk': ['"Hanken Grotesk"', 'sans-serif'],
        'material-symbols': ['"Material Symbols Outlined"'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px' }],
        'headline-lg': ['32px', { lineHeight: '40px' }],
        'headline-md': ['24px', { lineHeight: '32px' }],
        'body-lg': ['18px', { lineHeight: '28px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.1em' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em' }],
      },
      spacing: {
        'container-max': '1280px',
        gutter: '24px',
        'margin-desktop': '80px',
        'margin-mobile': '20px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'stack-xl': '64px',
      },
      maxWidth: {
        container: '1280px',
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
    },
  },
  plugins: [],
};
